<h1 style="text-align:center;color:white;background-color:#2471A3;padding:10px;border-radius:8px;">PRODUCTIVITY PREDICTION OF GARMENT EMPLOYEES</h1>

### Introduction to Productivity Presdiction of Garment Employees

**Productivity Prediction of Garment Employees** is a data analytics and machine learning project that focuses on analyzing employee productivity in the garment manufacturing industry.
The project uses factors such as working hours, overtime, incentives, number of workers, workload, and targeted productivity to identify patterns that influence performance. Using **Python**, the dataset is cleaned, explored, visualized, and analyzed to generate meaningful insights. 
Machine learning techniques can then be used to predict employee productivity and support better production planning and decision-making.

The main purpose of this analysis is to understand the key factors that influence the productivity of garment employees and identify patterns that can help improve production performance.
This project uses Python libraries such as **Pandas**,**Numpy**,**Plotly**,**Matplotlib**,and **Seaborn** to analyze a productivity dataset.

### Data Source
The dataset used in this project was collected through UCI machine learning repository,which directed me to the original dataset hosted on (https://archive.ics.uci.edu/dataset/597/productivity+prediction+of+garment+employees).

***Note:-*** The original file name was "garments_worker_productivity.csv",but I renamed it to "Productivity Prediction of Garment Employees.csv".Only the file name was changed;the data structure and contents remain unchanged.

### Attribute Details

<table style="width:100%; border-collapse: collapse;font-size:14px;">
    <thead>
  <tr>
    <th style="width:22%;text-align:left;padding:6px;border-bottom:2px solid #ccc;">Attribute Name</th>
    <th style="width:78%;text-align:left;padding:6px;border-bottom:2px solid #ccc;">Description</th>
      
  </tr>
    </thead>
    <tbody>

  <tr>
    <td style="padding:6px;">Date</td>
    <td style="padding:6px;">Date of production activity.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Day</td>
    <td style="padding:6px;">Day of the production week.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Quarter</td>
    <td style="padding:6px;">A portion of the month. A month was divided into four quarters.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Department</td>
    <td style="padding:6px;">Production department.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Team</td>
    <td style="padding:6px;">Team responsible for production.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Targeted Productivity</td>
    <td style="padding:6px;">Productivity target set for the team.</td>
  </tr>

  <tr>
    <td style="padding:6px;">SMV</td>
    <td style="padding:6px;">Standard Minute Value required for production.</td>
  </tr>

  <tr>
    <td style="padding:6px;">WIP</td>
    <td style="padding:6px;">Work in progress.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Over Time</td>
    <td style="padding:6px;">Amount of overtime worked.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Incentive</td>
    <td style="padding:6px;">Incentive provided to workers.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Idle Time</td>
    <td style="padding:6px;">Total idle time.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Idle Men</td>
    <td style="padding:6px;">Number of workers who were idle.</td>
  </tr>

   <tr>
    <td style="padding:6px;">No. of Style Changes</td>
    <td style="padding:6px;">Number of style changes during production.</td>
  </tr>

  <tr>
    <td style="padding:6px;">No. of Workers</td>
    <td style="padding:6px;">Number of workers involved.</td>
  </tr>

  <tr>
    <td style="padding:6px;">Actual Productivity</td>
    <td style="padding:6px;">Actual productivity achieved.</td>
  </tr>
  </tbody>
</table>

***Note:-*** **NaN** in WIP column means that the information is missing.  
***Info:-*** This dataset consists of 1197, Production records and 15 attributes.Providing a structured collection of dataset contains production and workforce-related attributes that can be used to study actual productivity.

### Imported Required Libraries
All neccessary Python libraries such as Pandas,Numpy,Plotly,Matplotlib,and Seaborn are imported for performing data loading,cleaning,exploration,and visualization.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Data Loading and Initial Overview
</h2>

In [ ]:
This step focuses on importing the dataset and understanding its basic structure before starting the preprocessing phase.

#### Importing Required Libraries
Imported Python libraries such as Pandas,and Numpy for data manipulation and numerical operations.

In [2]:
import pandas as pd
import numpy as np

### (i) Dataset Loading for Further Analysis

In [3]:
#Importing the Dataset
df=pd.read_csv(r"C:\Users\hp\Desktop\Productivity Prediction of Garment Employees.csv")

***Info:-*** Used Pandas to load the dataset into Python,so that it can be viewed,explored,and prepared for further analysis.

### (ii) Initial Overview of the Dataset

In [4]:
#Displaying the Dimensions of the Dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 1197
Number of Columns: 15

***Info:-*** Shows how many rows and columns are present.

In [5]:
#Displaying the First 5 Rows
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,01-01-2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,01-01-2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,01-01-2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,01-01-2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,01-01-2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

***Info:-*** Displays the first five rows of the dataset,providing a quick preview of the data format,column structure,and sample values.

In [6]:
#Checking DataFrame Structural Summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

***Info:-*** Provides a complete summary of the dataset.It displays the number of rows and columns,column names,non-null value counts,and data type of each column,as well as the memory usage of the DataFrame.Therefore it helps to identify which columns need preprocessing.

In [7]:
#Checking Missing Values
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

***Info:-*** Used to find how many missing values are present in each column.

In [8]:
#Displaying Statistical Summary
df.describe()

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,1197.000000,1197.000000,1197.000000,691.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
mean,6.426901,0.729632,15.062172,1190.465991,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
std,3.463963,0.097891,10.943219,1837.455001,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488
min,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,3.000000,0.700000,3.940000,774.500000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,9.000000,0.800000,24.260000,1252.500000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437

***Info:-*** Provides summary statistics for numerical features including mean,median,standard deviation,minimum and maximum values.

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Data Preprocessing
</h2>

This step ensures the dataset is clean,consistent,and suitable for analysis.The cleaning steps include (i)**Handling missing values**,(ii)**Removing duplicates**,(iii)**Creating Derived columns**,(iv)**Standardizing column names and Categorical values**(v)**Correcting Data Types**(vi)**Removing unnecessary columns**,(vii)**Filtering data**.

### (i)Handling Missing Values
The dataset contained **506** missing(NaN)values in the **WIP** column.Since WIP is a numerical feature,these missing/NaN entries were replaced using the median,which is more robust to outliers and preserves the overall distribution.This ensures the dataset remains complete and suitable for further preprocessing.

In [9]:
#Displaying the Missing(NaN)Values in the WIP Column
print("Missing(Nan)Values in the WIP Column:",df["wip"].isnull().sum())

Missing(Nan)Values in the WIP Column: 506

In [10]:
#Filling WIP missing values with Median
df["wip"]=df["wip"].fillna(df["wip"].median())

In [11]:
#After Replacing WIP missing values with Median
print("Missing(NaN)Values in the WIP Column:",df["wip"].isnull().sum())

Missing(NaN)Values in the WIP Column: 0

In [12]:
#Dispalying WIP Median Value
print("WIP Median Value:",df["wip"].median())

WIP Median Value: 1039.0

In [13]:
#Displaying Missing(NaN)Values Replaced with WIP Median Value(1039.0)
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,01-01-2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,01-01-2015,Quarter1,finishing,Thursday,1,0.75,3.94,1039.0,960,0,0.0,0,0,8.0,0.886500
2,01-01-2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,01-01-2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,01-01-2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

***Info:-*** The missing WIP value has been replaced with WIP Median Value and now appears as 1039.0 when viewing the first five rows using df.head().

### (ii)Removing Duplicates

In [14]:
#Checking the number of duplicate rows
print("Duplicate Rows Found:",df.duplicated().sum())

Duplicate Rows Found: 0

In [15]:
#Removing duplicates
print("Number of Duplicate Rows:",df.drop_duplicates(inplace=True))

Number of Duplicate Rows: None

In [16]:
#Checking the Dimensions of the Dataset
print("Dataset Dimensions:",df.shape)

Dataset Dimensions: (1197, 15)

***Info:-*** The dataset was checked for duplicate entries using df.duplicated().sum().The result returned 0 duplicates,indicating that no repeated rows were found.The drop_duplicates() function was applied as a standard preprocessing step,although no removal was required.

### (iii)Creating Derived Columns
**Derived columns**:New variables such as **year**, **month**, **month name**, and **productivity percentage** were derived from existing variables to support time-based analysis and improve the interpretation of productivity results.

In [17]:
#Displaying Columns Before Derived
print("Current column names:",df.columns.tolist())

Current column names: ['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers', 'actual_productivity']

***Info:-*** The dataset already has a useful date column, so we can create additional columns that make analysis easier.
First convert date into datetime format.

In [18]:
df['date'] = pd.to_datetime(
    df['date'],
    errors='coerce'
)

In [19]:
df.dtypes

date                     datetime64[ns]
quarter                          object
department                       object
day                              object
team                              int64
targeted_productivity           float64
smv                             float64
wip                             float64
over_time                         int64
incentive                         int64
idle_time                       float64
idle_men                          int64
no_of_style_change                int64
no_of_workers                   float64
actual_productivity             float64
dtype: object

***Info:-*** The datatype of date column is changed to datetime format.

In [20]:
#Now create:Year

df['year'] = df['date'].dt.year

In [21]:
#Now create:Month

df['month'] = df['date'].dt.month

In [22]:
#Now create:Month Name

df['month_name'] = df['date'].dt.month_name()

In [23]:
#Productivity Percentage
#Actual_productivity ranges approximately from 0 to 1. For easier interpretation, create:

df['productivity_percentage'] = df['actual_productivity'] * 100
df['productivity_percentage']

0       94.072542
1       88.650000
2       80.057049
3       80.057049
4       80.038194
          ...
1192    62.833333
1193    62.562500
1194    62.562500
1195    50.588889
1196    39.472222
Name: productivity_percentage, Length: 1197, dtype: float64

In [24]:
#Displaying Columns After Derived
print("Updated columns after creating Derived columns:",df.columns.tolist())

Updated columns after creating Derived columns: ['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers', 'actual_productivity', 'year', 'month', 'month_name', 'productivity_percentage']

### (iv)Standardizing  Column Names and Categorical Values
**Column names** contains lowercase letters and underscores, which is already fairly consistent.
However, there is an extra space after **finishing**, and **sweing** appears to be a spelling variation of sewing.

#### Remove Unnecessary spaces:

In [25]:
df['department']=df['department'].str.strip()

In [26]:
#Check:

df['department'].unique()

array(['sweing', 'finishing'], dtype=object)

#### Correct the spelling:

In [27]:
df['department'] = df['department'].replace({
    'sweing': 'sewing'
})

In [28]:
#Check:
df['department'].unique()

array(['sewing', 'finishing'], dtype=object)

In [29]:
#Standardizing Column Names
df.columns=df.columns.str.strip().str.replace("_"," ").str.title()

In [30]:
#Displaying Updated Column Names
print("Updated Column Names:",df.columns)

Updated Column Names: Index(['Date', 'Quarter', 'Department', 'Day', 'Team', 'Targeted Productivity',
       'Smv', 'Wip', 'Over Time', 'Incentive', 'Idle Time', 'Idle Men',
       'No Of Style Change', 'No Of Workers', 'Actual Productivity', 'Year',
       'Month', 'Month Name', 'Productivity Percentage'],
      dtype='object')

***Info:-***  **str.strip()** removes any leading or trailing spaces from column names to avoid hidden formatting issues.**str.replace("_"," ")** replaces underscores with spaces to make column names cleaner and more readable.**str.title()** converts each column name into Title Case,Categorical values in the **department** column were also cleaned by removing extra spaces and correcting the inconsistent spelling of the **sewing department**.

### (v)Correcting Data Types
In this step,the data types of certain columns are corrected to ensure consistent and efficient analysis.This include fixing numerical fields such as the **Date** column and updating **datetime** columns to more appropriate data types before further processing.

In [31]:
#Checking Data Types of Each Column Before Conversion 
df.dtypes

Date                       datetime64[ns]
Quarter                            object
Department                         object
Day                                object
Team                                int64
Targeted Productivity             float64
Smv                               float64
Wip                               float64
Over Time                           int64
Incentive                           int64
Idle Time                         float64
Idle Men                            int64
No Of Style Change                  int64
No Of Workers                     float64
Actual Productivity               float64
Year                              float64
Month                             float64
Month Name                         object
Productivity Percentage           float64
dtype: object

#### Convert date

In [32]:
df['Date'] = pd.to_datetime(
    df['Date'],
    errors='coerce'
)

In [33]:
#Check:
df['Date']

0      2015-01-01
1      2015-01-01
2      2015-01-01
3      2015-01-01
4      2015-01-01
          ...
1192   2015-03-11
1193   2015-03-11
1194   2015-03-11
1195   2015-03-11
1196   2015-03-11
Name: Date, Length: 1197, dtype: datetime64[ns]

In [34]:
#Check missing dates:
df['Date'].isnull().sum()

np.int64(562)

In [35]:
#use forward fill:
df['Date'] = df['Date'].ffill()

In [36]:
#Fill any remaining missing dates at the beginning
df['Date'] = df['Date'].bfill()

In [37]:
#Check again:
df['Date'].isnull().sum()

np.int64(0)

***Info:-***  **562** missing values were identified in the **Date** column.Instead of removing these records and losing valuable productivity information, the missing dates were handled using **forward-fill** based on the chronological order of the dataset. Any remaining missing values at the beginning of the dataset were handled using **backward-fill.** This approach helps preserve the available records while maintaining the temporal structure required for time-based analysis.

In [38]:
#Check missing Year:
df['Year'].isnull().sum()

np.int64(562)

In [39]:
#use forward fill:
df['Year'] = df['Year'].ffill()

In [40]:
#Fill any remaining missing Year at the beginning
df['Year'] = df['Year'].bfill()

In [41]:
#Check again:
df['Year'].isnull().sum()

np.int64(0)

***Info:-***  **562** missing values were identified in the **Year** column.Instead of removing these records and losing valuable productivity information, the missing years were handled using **forward-fill** based on the chronological order of the dataset. Any remaining missing values at the beginning of the dataset were handled using **backward-fill.** This approach helps preserve the available records while maintaining the temporal structure required for time-based analysis.

In [42]:
#Check missing Month:
df['Month'].isnull().sum()

np.int64(562)

In [43]:
#use forward fill:
df['Month'] = df['Month'].ffill()

In [44]:
#Fill any remaining missing Year at the beginning
df['Month'] = df['Month'].bfill()

In [45]:
#Check again:
df['Month'].isnull().sum()

np.int64(0)

***Info:-***  **562** missing values were identified in the **Month** column.Instead of removing these records and losing valuable productivity information, the missing years were handled using **forward-fill** based on the chronological order of the dataset. Any remaining missing values at the beginning of the dataset were handled using **backward-fill.** This approach helps preserve the available records while maintaining the temporal structure required for time-based analysis.

In [46]:
#Check missing Month Name:
df['Month Name'].isnull().sum()

np.int64(562)

In [47]:
#use forward fill:
df['Month Name'] = df['Month Name'].ffill()

In [48]:
#Fill any remaining missing Year at the beginning
df['Month Name'] = df['Month Name'].bfill()

In [49]:
#Check again:
df['Month Name'].isnull().sum()

np.int64(0)

***Info:-***  **562** missing values were identified in the **Month Name** column.Instead of removing these records and losing valuable productivity information, the missing years were handled using **forward-fill** based on the chronological order of the dataset. Any remaining missing values at the beginning of the dataset were handled using **backward-fill.** This approach helps preserve the available records while maintaining the temporal structure required for time-based analysis.

#### convert categorical columns:

In [50]:
categorical_columns = [
    'Quarter',
    'Department',
    'Day'
]

for col in categorical_columns:
    df[col] = df[col].astype('category')

In [51]:
#Displaying Columns with Category Data Type
df.dtypes[df.dtypes=="category"]

Quarter       category
Department    category
Day           category
dtype: object

***Info:-***  The data types of the variables were examined and corrected where necessary. The **Date** column was converted from object format to **datetime** format, while **categorical** variables were appropriately identified for analysis.

### (vi)Removing Unnecessary Columns

The Dataset has **15 original coloumns**.Not remove any of these columns at this stage.All of them can potentially provide useful information for your productivity analysis.

### (vii)Filtering Data

Filtering is the process of removing rows that are incorrect,irrelevant,or not useful for analysis.This step ensures the dataset only contains meaningful and valid observations.

#### Filtering :
Check whether there are invalid or irrelevant records.**Productivity** should logically be within the expected range.

##### (i) Check productivity

In [52]:
df['Actual Productivity'].min()

0.233705476

In [53]:
df['Actual Productivity'].max()

1.1204375

***Info:-***  The dataset description mentions a **productivity range of 0–1,** but your actual data contains values **above 1**. Therefore, do not automatically delete those records. They may represent **productivity exceeding the target/reference level.**

##### (ii)Check targeted productivity

In [54]:
df['Targeted Productivity'].min(), df['Targeted Productivity'].max()

(0.07, 0.8)

***Info:-***  **Targeted productivity values are within the expected range.**

##### (iii) Check invalid worker counts

In [55]:
df[df['No Of Workers'] <= 0]

Empty DataFrame
Columns: [Date, Quarter, Department, Day, Team, Targeted Productivity, Smv, Wip, Over Time, Incentive, Idle Time, Idle Men, No Of Style Change, No Of Workers, Actual Productivity, Year, Month, Month Name, Productivity Percentage]
Index: []

##### (iv) Check negative overtime

In [56]:
df[df['Over Time'] < 0]

Empty DataFrame
Columns: [Date, Quarter, Department, Day, Team, Targeted Productivity, Smv, Wip, Over Time, Incentive, Idle Time, Idle Men, No Of Style Change, No Of Workers, Actual Productivity, Year, Month, Month Name, Productivity Percentage]
Index: []

##### (v)  Check negative incentives

In [57]:
df[df['Incentive'] < 0]

Empty DataFrame
Columns: [Date, Quarter, Department, Day, Team, Targeted Productivity, Smv, Wip, Over Time, Incentive, Idle Time, Idle Men, No Of Style Change, No Of Workers, Actual Productivity, Year, Month, Month Name, Productivity Percentage]
Index: []

##### (vi)  Check negative idle time

In [58]:
df[df['Idle Time'] < 0]

Empty DataFrame
Columns: [Date, Quarter, Department, Day, Team, Targeted Productivity, Smv, Wip, Over Time, Incentive, Idle Time, Idle Men, No Of Style Change, No Of Workers, Actual Productivity, Year, Month, Month Name, Productivity Percentage]
Index: []

***Info:-***  These checks help identify potentially **invalid observations.**
The dataset was examined for invalid or unrealistic observations, including **negative working measures** and **invalid workforce values.** Records were retained when the values represented valid production observations, while potentially erroneous records were investigated before removal.

<div style=" margin-top:15px;background:#e7f9ed;padding:12px 16px;border-left:5px solid #2ecc71;border-radius:6px;font-family:Arial,sans-serif;font-weight:bold;color:#0d6b2d;">✔ Data Preprocessing was successfully completed !!  Ensuring the dataset is clean,consistent,and ready for analysis.</div>

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Exploratory Data Analysis (EDA)
</h2>

**Exploratory Data Analysis (EDA)** is the process of summarizing,visualizing,and understanding the underlying patterns,trends,relationships,and distributions within the dataset before modeling or decision making.

#### (i) Overview of the Dataset
Examine the dataset's size,data types using **df.shape**,**df.head()**,and **df.info()** to get an initial understanding of the data.

In [59]:
#Displaying the Dimensions of the Dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 1197
Number of Columns: 19

In [60]:
#Displaying the First 5 Rows
df.head()

,Date,Quarter,Department,Day,Team,Targeted Productivity,Smv,Wip,Over Time,Incentive,Idle Time,Idle Men,No Of Style Change,No Of Workers,Actual Productivity,Year,Month,Month Name,Productivity Percentage
0,2015-01-01,Quarter1,sewing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725,2015.0,1.0,January,94.072542
1,2015-01-01,Quarter1,finishing,Thursday,1,0.75,3.94,1039.0,960,0,0.0,0,0,8.0,0.886500,2015.0,1.0,January,88.650000
2,2015-01-01,Quarter1,sewing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,2015.0,1.0,January,80.057049
3,2015-01-01,Quarter1,sewing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,2015.0,1.0,January,80.057049
4,2015-01-01,Quarter1,sewing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382,2015.0,1.0,January,80.038194

In [61]:
#Checking Dataframe Structural Summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1197 non-null   datetime64[ns]
 1   Quarter                  1197 non-null   category
 2   Department               1197 non-null   category
 3   Day                      1197 non-null   category
 4   Team                     1197 non-null   int64
 5   Targeted Productivity    1197 non-null   float64
 6   Smv                      1197 non-null   float64
 7   Wip                      1197 non-null   float64
 8   Over Time                1197 non-null   int64
 9   Incentive                1197 non-null   int64
 10  Idle Time                1197 non-null   float64
 11  Idle Men                 1197 non-null   int64
 12  No Of Style Change       1197 non-null   int64
 13  No Of Workers            1197 non-null   float64
 14  Actual Productivity      1197 non-null   float64
 15  Year                     1197 non-null   float64
 16  Month                    1197 non-null   float64
 17  Month Name               1197 non-null   object
 18  Productivity Percentage  1197 non-null   float64
dtypes: category(3), datetime64[ns](1), float64(9), int64(5), object(1)
memory usage: 153.8+ KB

#### (ii) Univariate Analysis
It examines each feature individually to understand its basic distribution and key statistical properties.

#### Summary Statistics(Numerical Columns)
Summarizes numerical data through core metrics that describe its distribution and spread.

In [62]:
#Displaying Statistical Summary
df.describe()

,Date,Team,Targeted Productivity,Smv,Wip,Over Time,Incentive,Idle Time,Idle Men,No Of Style Change,No Of Workers,Actual Productivity,Year,Month,Productivity Percentage
count,1197,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.0,1197.000000,1197.000000
mean,2015-01-31 00:22:51.428571392,6.426901,0.729632,15.062172,1126.437761,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091,2015.0,1.724311,73.509110
min,2015-01-01 00:00:00,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705,2015.0,1.000000,23.370548
25%,2015-01-12 00:00:00,3.000000,0.700000,3.940000,970.000000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307,2015.0,1.000000,65.030714
50%,2015-02-03 00:00:00,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333,2015.0,2.000000,77.333333
75%,2015-02-12 00:00:00,9.000000,0.800000,24.260000,1083.000000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253,2015.0,2.000000,85.025253
max,2015-03-11 00:00:00,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437,2015.0,3.000000,112.043750
std,NaN,3.463963,0.097891,10.943219,1397.653191,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488,0.0,0.744558,17.448790

#### Frequency Distribution(Categorical Columns)
It involves examining all **categorical columns** to understand the different categories they contain and how **frequently** each category appears in the dataset.It helps identify dominant groups,rare categories,and any imbalance in the data.

In [63]:
for col in df.select_dtypes(include="category"):
    print("\nColumn:",col)
    print(df[col].value_counts())

Column: Quarter
Quarter
Quarter1    360
Quarter2    335
Quarter4    248
Quarter3    210
Quarter5     44
Name: count, dtype: int64

Column: Department
Department
sewing       691
finishing    506
Name: count, dtype: int64

Column: Day
Day
Wednesday    208
Sunday       203
Tuesday      201
Monday       199
Thursday     199
Saturday     187
Name: count, dtype: int64

***Info:-*** Frequency distributions were calculated for categorical columns to understand the number of observations in each category. This helped identify the most common **departments**, **quarters**, and **working days**, as well as detect missing or inconsistent categorical values.

#### (iii) Bivariate Analysis
Bivariate analysis means studying the relationship between two variables at a time, especially how different factors are related to actual_productivity.

##### 1. Numerical vs Numerical

In [64]:
# Correlation of numerical variables with actual productivity

numeric_cols = df.select_dtypes(include='number')

correlation = numeric_cols.corr()['Actual Productivity'].sort_values(
    ascending=False
)

print(correlation)

Actual Productivity        1.000000
Productivity Percentage    1.000000
Targeted Productivity      0.421594
Wip                        0.083545
Incentive                  0.076538
Over Time                 -0.054206
No Of Workers             -0.057991
Idle Time                 -0.080851
Month                     -0.092914
Smv                       -0.122089
Team                      -0.148753
Idle Men                  -0.181734
No Of Style Change        -0.207366
Year                            NaN
Name: Actual Productivity, dtype: float64

***Info:-*** This tells you how strongly each **numerical variable** is related to productivity.Targeted Productivity has the strongest positive relationship with Actual Productivity **(0.421594)**, indicating a moderate association. Most other numerical variables show weak or very weak relationships with actual productivity. No. of Style Changes (-0.207366) has the strongest negative relationship, suggesting that increased style changes may be associated with slightly lower productivity.

##### 2. Targeted Productivity vs Actual Productivity

In [65]:
df[['Targeted Productivity', 'Actual Productivity']].corr()

                       Targeted Productivity  Actual Productivity
Targeted Productivity               1.000000             0.421594
Actual Productivity                 0.421594             1.000000

***Info:-*** The correlation between Targeted Productivity and **Actual Productivity is 0.421594**The correlation is **positive**, meaning higher targeted productivity is generally associated with higher actual productivity.

#### 3. Number of Workers vs Actual Productivity

In [66]:
df[['No Of Workers', 'Actual Productivity']].corr()

                     No Of Workers  Actual Productivity
No Of Workers             1.000000            -0.057991
Actual Productivity      -0.057991             1.000000

***Info:-*** The correlation between Number of Workers and Actual Productivity is **-0.057991**, indicating a **very weak negative relationship**. This suggests that the number of workers has little direct association with actual productivity.

#### Categorical vs Numerical

#### 4. Department vs Actual Productivity

In [69]:
df.groupby('Department')['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
)

C:\Users\hp\AppData\Local\Temp\ipykernel_9260\3044778263.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Department')['Actual Productivity'].agg(

            count      mean       min       max
Department
finishing     506  0.752951  0.235795  1.120437
sewing        691  0.722013  0.233705  1.100484

***Info:-*** The bivariate analysis shows that the **Finishing department** has a higher average actual productivity **(0.752951)** compared with the **Sewing department (0.722013)**. This indicates that productivity performance varies across departments, with the Finishing department showing slightly better average productivity.

#### 5. Quarter vs Actual Productivity

In [70]:
df.groupby('Quarter')['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
)

C:\Users\hp\AppData\Local\Temp\ipykernel_9260\2468897130.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Quarter')['Actual Productivity'].agg(

          count      mean       min       max
Quarter
Quarter1    360  0.751560  0.260979  1.050667
Quarter2    335  0.743710  0.233705  1.100484
Quarter3    210  0.704759  0.235795  1.120437
Quarter4    248  0.709067  0.259375  1.059621
Quarter5     44  0.826177  0.286985  1.000457

***Info:-*** Actual productivity varies across quarters. **Quarter 5 has the highest average productivity (0.826177)**, while **Quarter 3** has the **lowest (0.704759)**. This indicates that productivity performance differs across quarters.

#### 6. Team vs Actual Productivity

In [71]:
df.groupby('Team')['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
)

      count      mean       min       max
Team
1       105  0.821054  0.268214  1.120437
2       109  0.770855  0.247316  1.108125
3        95  0.803880  0.256500  1.059621
4       105  0.770035  0.287042  1.096633
5        93  0.697981  0.233705  1.033570
6        94  0.685385  0.263694  0.977556
7        96  0.668006  0.258000  0.999533
8       109  0.674148  0.251399  1.011562
9       104  0.734462  0.238042  0.994271
10      100  0.719736  0.235795  0.999995
11       88  0.681985  0.259375  0.987880
12       99  0.779055  0.272000  1.020000

***Info:-*** Actual productivity varies across teams. **Team 1 has the highest average productivity (0.821054)**, while **Team 7 has the lowest (0.668006)**. This indicates that productivity performance differs noticeably between teams.

#### (iv) Multivariate Analysis
It examines how multiple variables interact simultaneously to uncover deeper patterns,combined effects,and factors influencing the target outcome.

In [72]:
print("Department + Quarter + Actual Productivity")
print(df.groupby(['Department', 'Quarter'])['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
))

print("\nTeam + Department + Actual Productivity")
print(df.groupby(['Team', 'Department'])['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
))

print("\nTeam + Quarter + Actual Productivity")
print(df.groupby(['Team', 'Quarter'])['Actual Productivity'].agg(
    ['count', 'mean', 'min', 'max']
))

Department + Quarter + Actual Productivity
                     count      mean       min       max
Department Quarter
finishing  Quarter1    149  0.758482  0.280333  1.050667
           Quarter2    147  0.764824  0.238042  1.096633
           Quarter3     81  0.735793  0.235795  1.120437
           Quarter4    108  0.713400  0.259375  1.059621
           Quarter5     21  0.900174  0.492500  0.989000
sewing     Quarter1    211  0.746671  0.260979  1.050281
           Quarter2    188  0.727200  0.233705  1.100484
           Quarter3    129  0.685272  0.249417  1.000230
           Quarter4    140  0.705725  0.268214  1.000230
           Quarter5     23  0.758615  0.286985  1.000457

Team + Department + Actual Productivity
                 count      mean       min       max
Team Department
1    finishing      49  0.827803  0.448722  1.120437
     sewing         56  0.815150  0.268214  1.100484
2    finishing      52  0.780130  0.247316  1.108125
     sewing         57  0.762394  0.302770  1.050281
3    finishing      37  0.847327  0.256500  1.059621
     sewing         58  0.776163  0.350302  1.000457
4    finishing      46  0.820643  0.287042  1.096633
     sewing         59  0.730577  0.350633  0.900800
5    finishing      35  0.791600  0.330114  1.033570
     sewing         58  0.641486  0.233705  0.800980
6    finishing      35  0.627926  0.271875  0.977556
     sewing         59  0.719471  0.263694  0.879714
7    finishing      41  0.685844  0.258000  0.999533
     sewing         55  0.654707  0.285333  0.900145
8    finishing      53  0.692657  0.264062  1.011562
     sewing         56  0.656631  0.251399  0.940725
9    finishing      46  0.724527  0.238042  0.994271
     sewing         58  0.742341  0.283054  0.970817
10   finishing      43  0.723417  0.235795  0.997792
     sewing         57  0.716959  0.249417  0.999995
11   finishing      29  0.693825  0.259375  0.987880
     sewing         59  0.676165  0.349951  0.821113
12   finishing      40  0.792333  0.272000  1.020000
     sewing         59  0.770054  0.350218  0.850521

Team + Quarter + Actual Productivity
               count      mean       min       max
Team Quarter
1    Quarter1     36  0.827259  0.448722  1.000602
     Quarter2     32  0.872674  0.618361  1.100484
     Quarter3     14  0.807099  0.403242  1.120437
     Quarter4     19  0.719904  0.268214  0.970076
     Quarter5      4  0.881564  0.850362  0.971867
2    Quarter1     34  0.795072  0.302770  1.050667
     Quarter2     31  0.797198  0.247316  1.057963
     Quarter3     16  0.696241  0.328132  1.108125
     Quarter4     24  0.724671  0.325000  1.000230
     Quarter5      4  0.936415  0.773333  1.000230
3    Quarter1     28  0.860670  0.750243  1.000230
     Quarter2     25  0.782838  0.350302  0.951944
     Quarter3     15  0.684361  0.256500  0.864583
     Quarter4     23  0.826889  0.460579  1.059621
     Quarter5      4  0.853753  0.492500  1.000457
4    Quarter1     34  0.731379  0.350706  0.988025
     Quarter2     30  0.793125  0.350633  1.096633
     Quarter3     19  0.746393  0.287042  0.988636
     Quarter4     18  0.791631  0.495618  0.963699
     Quarter5      4  0.940551  0.900537  0.989000
5    Quarter1     22  0.613467  0.330114  0.805750
     Quarter2     28  0.675356  0.233705  0.909392
     Quarter3     20  0.755172  0.452013  1.033570
     Quarter4     20  0.748670  0.307501  0.973797
     Quarter5      3  0.809701  0.656764  0.971867
6    Quarter1     27  0.652409  0.263694  0.942500
     Quarter2     24  0.679393  0.271875  0.888125
     Quarter3     18  0.758662  0.465758  0.936861
     Quarter4     21  0.660863  0.271875  0.977556
     Quarter5      4  0.742924  0.500118  0.971867
7    Quarter1     32  0.678134  0.295308  0.999533
     Quarter2     25  0.680735  0.350302  0.929278
     Quarter3     17  0.663405  0.258000  0.913750
     Quarter4     19  0.646492  0.283958  0.957639
     Quarter5      3  0.616206  0.388830  0.971867
8    Quarter1     32  0.714879  0.260979  1.011562
     Quarter2     32  0.670262  0.264062  0.994375
     Quarter3     20  0.671228  0.251399  0.850416
     Quarter4     22  0.618030  0.329545  0.930417
     Quarter5      3  0.712134  0.286985  0.971867
9    Quarter1     31  0.788677  0.447083  0.994271
     Quarter2     31  0.761759  0.238042  0.929074
     Quarter3     20  0.700270  0.283054  0.964106
     Quarter4     19  0.612761  0.261174  0.970817
     Quarter5      3  0.890882  0.850170  0.971867
10   Quarter1     30  0.772450  0.463194  0.999995
     Quarter2     25  0.669065  0.246250  0.912767
     Quarter3     17  0.615544  0.235795  0.974621
     Quarter4     24  0.748336  0.385792  0.997792
     Quarter5      4  0.912296  0.856950  0.971867
11   Quarter1     25  0.739328  0.345833  0.987880
     Quarter2     26  0.684283  0.349951  0.960625
     Quarter3     17  0.611772  0.313853  0.838384
     Quarter4     16  0.640798  0.259375  0.896023
     Quarter5      4  0.771799  0.600598  0.971867
12   Quarter1     29  0.792713  0.607654  0.906667
     Quarter2     26  0.820180  0.272000  1.020000
     Quarter3     17  0.751858  0.350218  0.991800
     Quarter4     23  0.735814  0.327407  0.902500
     Quarter5      4  0.776957  0.634667  0.971867

C:\Users\hp\AppData\Local\Temp\ipykernel_9260\2416010389.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(['Department', 'Quarter'])['Actual Productivity'].agg(
C:\Users\hp\AppData\Local\Temp\ipykernel_9260\2416010389.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(['Team', 'Department'])['Actual Productivity'].agg(
C:\Users\hp\AppData\Local\Temp\ipykernel_9260\2416010389.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(['Team', 'Quarter'])['Actual Productivity'].agg(

***Purpose:-*** Multivariate analysis was performed by examining actual productivity across multiple variables simultaneously, including **department, team, and quarter**. Groupby analysis was used to identify how productivity varies across different combinations of these factors. This helped identify differences in productivity performance among teams, departments, and production periods.

#### (v) Missing Value Analysis
Final verification to ensure that the dataset has no missing values after preprocessing.

In [73]:
#Confirming Data Completeness
df.isnull().sum()

Date                       0
Quarter                    0
Department                 0
Day                        0
Team                       0
Targeted Productivity      0
Smv                        0
Wip                        0
Over Time                  0
Incentive                  0
Idle Time                  0
Idle Men                   0
No Of Style Change         0
No Of Workers              0
Actual Productivity        0
Year                       0
Month                      0
Month Name                 0
Productivity Percentage    0
dtype: int64

<div style=" margin-top:15px;background:#e7f9ed;padding:12px 16px;border-left:5px solid #2ecc71;border-radius:6px;font-family:Arial,sans-serif;font-weight:bold;color:#0d6b2d;">✔ EDA was successfully performed to understand the dataset.</div>

#### Save cleaned dataset to a new CSV file

In [76]:
df.to_csv("cleaned Dataset Productivity Prediction of Garment Employees data.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!