**PRODUCTIVITY PREDICTION OF GARMENT EMPLOYEES**

In [ ]:
# The dataset used in this project was obtained from UCI Machine Learning Repository.

In [ ]:
# This dataset includes important attributes of the garment manufacturing process and the productivity of the employees.

In [ ]:
# The Garment Industry is a labour-intensive industry where employee performance plays an important role in meeting production demands.

In [ ]:
# This project focuses on analyzing and predicting the productivity of garment employees based on factors such as
 - Working hours
 - Incentives
 - Workload 
 - Number of workers

In [ ]:
# The project is to analyze and predict the productivity of garment employees using Python, data analytics, and machine learning techniques.

**1) Data Loading and Initial Overview**

In [ ]:
# Import the Data Set using Pandas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\hp\Desktop\Productivity Prediction of Garment Employees.csv")
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,01-01-2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,01-01-2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,01-01-2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,01-01-2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,01-01-2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

**Dataset Overview**

**The dataset contains production and workforce-related attributes that can be used to study actual productivity.**

- Date  - Date of production activity
- Day   - Day of the production week
- Quarter - A portion of the month. A month was divided into four quarters
- Department - Production department
- Team	     - Team responsible for production
- Targeted Productivity	- Productivity target set for the team
- SMV	 - Standard Minute Value required for production
- WIP	 - Work in progress
- Over Time	- Amount of overtime worked
- Incentive	- Incentive provided to workers
- Idle Time	- Total idle time
- Idle Men	- Number of workers who were idle
- No. of Style Changes	- Number of style changes during production
- No. of Workers	    - Number of workers involved
- Actual Productivity	- Actual productivity achieved

**Dataset Characteristics**

- Number of Records: Rows = 1197 ,Columns = 15
- Numerical and categorical variables
- Date-related information
- Exploratory Data Analysis (EDA) and Machine Learning

**Descriptive Analysis**

In [4]:
df.shape

(1197, 15)

In [5]:
df.dtypes

date                      object
quarter                   object
department                object
day                       object
team                       int64
targeted_productivity    float64
smv                      float64
wip                      float64
over_time                  int64
incentive                  int64
idle_time                float64
idle_men                   int64
no_of_style_change         int64
no_of_workers            float64
actual_productivity      float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

**2) Data Pre-processing**

● Perform all necessary cleaning steps such as:

- Handling Missing Values
- Check duplicate records
- Remove duplicate records
- Fill missing values (NaN) with 0
- Data type conversion

**Handling Missing Values**

In [11]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

**Missing values in numerical columns**

In [12]:
num_cols=df.select_dtypes(include=['float64','int64']).columns
for col in num_cols:
    df[col].fillna(df[col].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_2212\1336701965.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    1197 non-null   float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

In [15]:
df.isnull().sum()

date                     0
quarter                  0
department               0
day                      0
team                     0
targeted_productivity    0
smv                      0
wip                      0
over_time                0
incentive                0
idle_time                0
idle_men                 0
no_of_style_change       0
no_of_workers            0
actual_productivity      0
dtype: int64

**Check duplicate records**

In [16]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

**Remove duplicate records**

In [17]:
df = df.drop_duplicates()
print("Number of duplicate rows after cleaning:", df.duplicated().sum())

Number of duplicate rows after cleaning: 0

In [18]:
df.columns

Index(['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity',
       'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men',
       'no_of_style_change', 'no_of_workers', 'actual_productivity'],
      dtype='object')

**Fill missing values (NaN) with 0**

In [19]:
df['wip'] = df['wip'].fillna(0)

In [20]:
df['wip']

0       1108.0
1       1039.0
2        968.0
3        968.0
4       1170.0
         ...
1192    1039.0
1193    1039.0
1194    1039.0
1195    1039.0
1196    1039.0
Name: wip, Length: 1197, dtype: float64

**Data type conversion**

**convert date column**

In [21]:
df['date'] = pd.to_datetime(
    df['date'],
    errors='coerce'
)

In [22]:
df.dtypes

date                     datetime64[ns]
quarter                          object
department                       object
day                              object
team                              int64
targeted_productivity           float64
smv                             float64
wip                             float64
over_time                         int64
incentive                         int64
idle_time                       float64
idle_men                          int64
no_of_style_change                int64
no_of_workers                   float64
actual_productivity             float64
dtype: object

**3) Exploratory Data Analysis (EDA)**

**Descriptive statistics for the numerical columns**

In [23]:
df.describe()

,date,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,635,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
mean,2015-02-05 07:47:08.976377856,6.426901,0.729632,15.062172,1126.437761,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
min,2015-01-01 00:00:00,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,2015-01-10 00:00:00,3.000000,0.700000,3.940000,970.000000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,2015-02-07 00:00:00,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,2015-03-03 00:00:00,9.000000,0.800000,24.260000,1083.000000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,2015-03-11 00:00:00,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437
std,NaN,3.463963,0.097891,10.943219,1397.653191,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488

**Cleaned Dataset saved to csv file**

In [24]:
df.to_csv("cleaned_dataset_Productivity_Prediction_ of Garment_Employees_data.csv", index=False)